const USER_CREATE_ROOM = "USER_CREATE_ROOM";
const USER_CREATED_ROOM = "USER_CREATED_ROOM";
const USER_JOIN_ROOM = "USER_JOIN_ROOM";
const USER_JOINED_ROOM = "USER_JOINED_ROOM";

module.exports = {
  USER_CREATE_ROOM,
  USER_CREATED_ROOM,
  USER_JOIN_ROOM,
  USER_JOINED_ROOM,
};
