const USER_CREATE_ROOM = "USER_CREATE_ROOM";
const USER_CREATED_ROOM = "USER_CREATED_ROOM";
const USER_JOIN_ROOM = "USER_JOIN_ROOM";
const USER_JOINED_ROOM = "USER_JOINED_ROOM";
const USER_JOIN_ROOM_FAILED = "USER_JOIN_ROOM_FAILED";
const USER_SET_NAME = "USER_SET_NAME";
const USER_SET_NAME_SUCCESS = "USER_SET_NAME_SUCCESS";
const USER_SET_NAME_FAILED = "USER_SET_NAME_FAILED";

module.exports = {
  USER_CREATE_ROOM,
  USER_CREATED_ROOM,
  USER_JOIN_ROOM,
  USER_JOINED_ROOM,
  USER_JOIN_ROOM_FAILED,
  USER_SET_NAME,
  USER_SET_NAME_FAILED,
  USER_SET_NAME_SUCCESS,
};
